### PR TITLE
Remove bulk of docs explanation in the checklist

### PR DESCRIPTION
**Pull request by kytrinyx**
There is now better documentation for this in the docs repository.
Link to that instead.

### CODE REVIEW

**Comment by Insti** [comment]
(Possibly unrelated to this PR.)
Should this file be called `CHECKLIST.md`?

**Comment by kytrinyx** [comment]
> Edit: Apparently it's a magic github file?

No, it's a file that I made which is used when generating new language tracks. It can be called whatever we want, as long as it matches the name in the `bin/bootstrap` script.

**Comment by Insti** [comment]
> It can be called whatever we want, as long as it matches the name in the bin/bootstrap script.

In which case can we rename it to `CONTRIBUTING.md` since it is a markdown file and so it renders nicely when viewing the file through github?

**Comment by kytrinyx** [comment]
Sure, works for me.

**Pull request merged**
